#!/usr/bin/env bash

set -e -u -o pipefail

CC_WRAPPER_PATH="CC_wrapper.sh"

source $CC_WRAPPER_PATH

time=4
account=def-chdesa
save_dir=0722_prostate_our
declare -a StringArray=(
# disp0
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=False Scheduler.RegScheduler.max_value=0.0000005   Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp0_501Ent_605joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=False Scheduler.RegScheduler.max_value=0.0000001   Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp0_501Ent_601joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=False Scheduler.RegScheduler.max_value=0.00000001  Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp0_501Ent_701joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=False Scheduler.RegScheduler.max_value=0.00000005  Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp0_501Ent_705joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=False Scheduler.RegScheduler.max_value=0.000000001 Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp0_501Ent_801joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=False Scheduler.RegScheduler.max_value=0.000000005 Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp0_501Ent_805joint_seed1"

# disp1 disp3
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=True Scheduler.RegScheduler.max_value=0.0000005   Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp1_501Ent_605joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=True Scheduler.RegScheduler.max_value=0.0000001   Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp1_501Ent_601joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=True Scheduler.RegScheduler.max_value=0.00000001  Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp1_501Ent_701joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=True Scheduler.RegScheduler.max_value=0.00000005  Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp1_501Ent_705joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=True Scheduler.RegScheduler.max_value=0.000000001 Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp1_501Ent_801joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=True Scheduler.RegScheduler.max_value=0.000000005 Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp1_501Ent_805joint_seed1"

"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=True DA.displace_scale=3 Scheduler.RegScheduler.max_value=0.0000005   Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp3_501Ent_605joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=True DA.displace_scale=3 Scheduler.RegScheduler.max_value=0.0000001   Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp3_501Ent_601joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=True DA.displace_scale=3 Scheduler.RegScheduler.max_value=0.00000001  Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp3_501Ent_701joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=True DA.displace_scale=3 Scheduler.RegScheduler.max_value=0.00000005  Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp3_501Ent_705joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=True DA.displace_scale=3 Scheduler.RegScheduler.max_value=0.000000001 Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp3_501Ent_801joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Deconv_1x1 DA.multi_scale=1 DA.displacement=True DA.displace_scale=3 Scheduler.RegScheduler.max_value=0.000000005 Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp3_501Ent_805joint_seed1"

# upconv2 disp0 disp1 disp 3
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=False DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.005  Scheduler.ClusterScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/upconv2_cc_401Ent_205joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=False DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.001  Scheduler.ClusterScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/upconv2_cc_401Ent_201joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=False DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.0001 Scheduler.ClusterScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/upconv2_cc_401Ent_301joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=False DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.0005 Scheduler.ClusterScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/upconv2_cc_401Ent_305joint_seed1"

"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=True DA.displace_scale=1 DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.005  Scheduler.ClusterScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/upconv2_cc1_401Ent_205joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=True DA.displace_scale=1 DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.001  Scheduler.ClusterScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/upconv2_cc1_401Ent_201joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=True DA.displace_scale=1 DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.0001 Scheduler.ClusterScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/upconv2_cc1_401Ent_301joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=True DA.displace_scale=1 DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.0005 Scheduler.ClusterScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/upconv2_cc1_401Ent_305joint_seed1"

"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=True DA.displace_scale=3 DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.005  Scheduler.ClusterScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/upconv2_cc3_401Ent_205joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=True DA.displace_scale=3 DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.001  Scheduler.ClusterScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/upconv2_cc3_401Ent_201joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=True DA.displace_scale=3 DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.0001 Scheduler.ClusterScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/upconv2_cc3_401Ent_301joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=True DA.displace_scale=3 DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.0005 Scheduler.ClusterScheduler.max_value=0.00001 Trainer.save_dir=${save_dir}/upconv2_cc3_401Ent_305joint_seed1"
###
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=False DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.005  Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/upconv2_cc_501Ent_205joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=False DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.001  Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/upconv2_cc_501Ent_201joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=False DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.0001 Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/upconv2_cc_501Ent_301joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=False DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.0005 Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/upconv2_cc_501Ent_305joint_seed1"

"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=True DA.displace_scale=1 DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.005  Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/upconv2_cc1_501Ent_205joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=True DA.displace_scale=1 DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.001  Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/upconv2_cc1_501Ent_201joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=True DA.displace_scale=1 DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.0001 Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/upconv2_cc1_501Ent_301joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=True DA.displace_scale=1 DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.0005 Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/upconv2_cc1_501Ent_305joint_seed1"

"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=True DA.displace_scale=3 DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.005  Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/upconv2_cc3_501Ent_205joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=True DA.displace_scale=3 DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.001  Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/upconv2_cc3_501Ent_201joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=True DA.displace_scale=3 DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.0001 Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/upconv2_cc3_501Ent_301joint_seed1"
"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=align_IndividualBN DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=1 DA.displacement=True DA.displace_scale=3 DA.align_layer.cc_based=True Scheduler.RegScheduler.max_value=0.0005 Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/upconv2_cc3_501Ent_305joint_seed1"

# bothlayer
#"python main.py seed=10 Optim.lr=0.00001 Data_input.dataset=prostate Data_input.num_class=2 Data.kfold=0 Trainer.name=combinationlayer DA.double_bn=True DA.batchsize_indicator=9 DA.statistic=True DA.align_layer.name=Up_conv2 DA.multi_scale=3 DA.displacement=True DA.align_layer.cc_based=True DA.weight1=100 Scheduler.RegScheduler.max_value=0.000001 Scheduler.ClusterScheduler.max_value=0.000001 Trainer.save_dir=${save_dir}/disp1r3_100bothlayer_501Ent_501joint_seed1"


)


for cmd in "${StringArray[@]}"; do
  echo ${cmd}
  CC_wrapper "${time}" "${account}" "${cmd}" 16

done
