Data_input:
  dataset: mmwhs
  num_class: 5

Optim:
  lr: 0.000001

Data:
  seed: 12

DataLoader:
  batch_size: 1 # must be 1
  val_batch_size: 1
  shuffle: False # must be false
  num_workers: 8
  pin_memory: False

Scheduler:
  RegScheduler:
    begin_epoch: 5
    max_epoch: 50
    min_value: 0
    max_value: 0
  ClusterScheduler:
    begin_epoch: 5
    max_epoch: 50
    min_value: 0
    max_value: 0

Trainer:
  name: align_IndividualBN # baseline entda  supervised  align_IndividualBN upperbaseline, combinationlayer, ottrainer, priorbased
  device: cuda
  save_dir: runs
  checkpoint_path: runs
  enable_sampling: true

DA:
  batchsize_indicator: 1 # 1:3 3:12  6: 21
  double_bn: False
  displacement: False
  multi_scale: 6 # 1, 2, 3, 4, 5, 6 Note: 1 refers to without multi_scale resilution
  source: MRI
  target: CT
  weight1: 1
  weight2: 1
  align_layer:
    name: Deconv_1x1 # Up_conv5, Up_conv4, Up_conv3, Up_conv2, Deconv_1x1
    clusters: 5

seed: 123