Data_input:
  dataset: mmwhs
  num_class: 5

Optim:
  lr: 0.000001

Data:
  seed: 12

DataLoader:
  batch_size: 5 # must be 1
  val_batch_size: 40
  shuffle: False # must be false
  num_workers: 0
  pin_memory: False

weights:
  consistency: 1
  structual: 1

Trainer:
  device: cuda
  save_dir: runs
  checkpoint_path: runs
  enable_sampling: true

DA:
  constrastve_sampler: False
  batchsize_indicator: 1

seed: 123