Data_input:
  dataset: mmwhs
  num_class: 5

Optim:
  lr: 0.00001

Data:
  seed: 12

DataLoader:
  batch_size: 1 # must be 1
  val_batch_size: 40
  shuffle: False # must be false
  num_workers: 8
  pin_memory: False

Scheduler:
  SemanticRegScheduler:
    begin_epoch: 5
    max_epoch: 50
    min_value: 0
    max_value: 0
  StructureScheduler:
    begin_epoch: 5
    max_epoch: 50
    min_value: 0
    max_value: 0

Trainer:
  device: cuda
  save_dir: runs
  checkpoint_path: runs
  enable_sampling: true

DA:
  constrastve_sampler: False
  batchsize_indicator: 1 # partition=7, bs=batchsize_indicator * 7

seed: 123