Data_input:
  dataset: mmwhs
  num_class: 5

Optim:
  lr: 0.000001
  disc_lr: 0.000001

Data:
  seed: 12
  kfold: 0

DataLoader:
  batch_size: 5 # must be 1
  val_batch_size: 40
  shuffle: False # must be false
  num_workers: 8
  pin_memory: False

weights: 0.2


Trainer:
  device: cuda
  save_dir: runs
  checkpoint_path: runs
  enable_sampling: true

DA:
  constrastve_sampler: False
  batchsize_indicator: 1
  double_bn: True

seed: 123