Data_input:
  dataset: mmwhs
  num_class: 5

Optim:
  lr: 0.0002
  disc_lr: 0.00001

Data:
  seed: 12

DataLoader:
  batch_size: 1 # must be 1
  val_batch_size: 40
  shuffle: False # must be false
  num_workers: 8
  pin_memory: False

Scheduler:
  RegScheduler_advs:
    begin_epoch: 5
    max_epoch: 50
    min_value: 0.1
    max_value: 0.1

  RegScheduler_cyc:
    begin_epoch: 5
    max_epoch: 50
    min_value: 10
    max_value: 10

  RegScheduler_seg2:
    begin_epoch: 5
    max_epoch: 50
    min_value: 0
    max_value: 0.1

  RegScheduler_advp1:
    begin_epoch: 5
    max_epoch: 50
    min_value: 0.1
    max_value: 0.1

  RegScheduler_advp2:
    begin_epoch: 5
    max_epoch: 50
    min_value: 0
    max_value: 0.01

  RegScheduler_advss:
    begin_epoch: 5
    max_epoch: 50
    min_value: 0.1
    max_value: 0.1

Trainer:
  device: cuda
  save_dir: runs
  checkpoint_path: runs
  enable_sampling: true

DA:
  batchsize_indicator: 1 # partition=7, bs=batchsize_indicator * 7
  source: MRI # promise
  target: CT  # prostate

seed: 123